public with sharing class NumberCount 
{
	public static String getString()
	{
		/*Integer origional = 1234;
		Integer i = origional;
		String text= '';
		if(math.mod(i,1000) != 0)
		{
		    text = ''+String.valueOf(i).chareAt(0);
		    i = math.mod(i,1000);
		    text += ''+String.valueOf(i).chareAt(0);
		    if(math.mod(i,100) != 0 )
		    {
		        i = math.mod(i,100);
		        text += ''+String.valueOf(i).chareAt(0);
		    }
		    if(math.mod(i,10) != 0)
		    {
		        i = math.mod(i,100);
		        text += ''+String.valueOf(i).chareAt(0);
		    }
		System.debug(text+' only');*/
		return '';
	}
}